apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod-mainnet
  labels:
    app: frontend-pod-mainnet
spec:
  restartPolicy: Never
  containers:
  - name: frontend-mainnet
    image: data-hub/frontend-mainnet
    imagePullPolicy: Never
---