apiVersion: v1
kind: Service
metadata:
  labels:
    app: timescaledb-service
  name: timescaledb-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: timescaledb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: timescaledb
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - name: timescaledb
        # image: timescale/timescaledb:latest-pg14
        image: timescale/timescaledb-ha:pg14-latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 700m
            memory: 2.5Gi
          requests:
            cpu: 700m
            memory: 2.5Gi
        env:
        - name: POSTGRES_PASSWORD
          value: ilovetimescaledb          
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: ubuntu/zookeeper:edge
        ports:
        - containerPort: 2181
          name: zookeeper
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-pod
spec:
  ports:
    - port: 9092
      targetPort: 9093
  selector:
    app: kafka-pod
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kafka-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka
#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#       - name: kafka
#         image: ubuntu/kafka:latest
#         env:
#           - name: ZOOKEEPER_HOST
#             value: zookeeper-service
#         args: ["/etc/kafka/server.properties", "--override", "advertised.listeners=INTERNAL://127.0.0.1:9092,EXTERNAL://kafka-service:9092", "--override", "listeners=INTERNAL://127.0.0.1:9092,EXTERNAL://0.0.0.0:9093", "--override", "listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT", "--override","inter.broker.listener.name=INTERNAL"]
#         ports:
#         - containerPort: 9092
#           name: kafka
#           protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
  labels:
    app: kafka-pod
spec:
  volumes:
  - name: kafka-pv-storage
    persistentVolumeClaim:
      claimName: kafka-pv-claim
  restartPolicy: Never
  containers:
  - name: kafka
    image: ubuntu/kafka:latest
    resources:
      limits:
        cpu: 500m
        memory: 2500Mi
      requests:
        cpu: 500m
        memory: 2500Mi
    env:
    - name: ZOOKEEPER_HOST
      value: zookeeper-service
    args: [ "/etc/kafka/server.properties", "--override", "advertised.listeners=INTERNAL://127.0.0.1:9092,EXTERNAL://kafka-service:9092", "--override", "listeners=INTERNAL://127.0.0.1:9092,EXTERNAL://0.0.0.0:9093", "--override", "listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT", "--override", "inter.broker.listener.name=INTERNAL", "--override", "message.max.bytes=2097152" ]
    ports:
    - containerPort: 9092
      name: kafka
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-volume
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kafka-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: positions-pod
  labels:
    app: positions-pod
spec:
  restartPolicy: Never
  containers:
  - name: positions
    image: data-hub/positions
    imagePullPolicy: Never
    env:
    - name: KAFKA_BROKERS
      value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
    - name: TIMESCALEDB_HOST
      value: timescaledb-service
    - name: TIMESCALEDB_PORT
      value: "5432"
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: query-test
#   name: query-test
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: query-test
#   template:
#     metadata:
#       labels:
#         app: query-test
#     spec:
#       containers:
#       - name: query
#         image: data-hub/query
#         imagePullPolicy: Never
#         resources:
#           limits:
#             cpu: 500m
#             memory: 1500Mi
#           requests:
#             cpu: 500m
#             memory: 1500Mi
#         env:
#         - name: KAFKA_BROKERS
#           value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trades-test
  name: trades-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades-test
  template:
    metadata:
      labels:
        app: trades-test
    spec:
      containers:
      - name: trades
        image: data-hub/trades
        imagePullPolicy: Never
        env:
        - name: KAFKA_SERVICE
          value: kafka-service
        - name: KAFKA_BROKERS
          value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
        - name: TIMESCALEDB_HOST
          value: timescaledb-service
        - name: TIMESCALEDB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-service
  name: api-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: data-hub/api
        imagePullPolicy: Never 
        ports:
        - containerPort: 8080
        env:
        - name: TIMESCALEDB_HOST
          value: timescaledb-service
        - name: TIMESCALEDB_PORT
          value: "5432"
---
apiVersion: v1
kind: Pod
metadata:
  name: vega-node-pod
  labels:
    app: vega-node-pod
spec:
  volumes:
  - name: vega-node-pv-storage
    persistentVolumeClaim:
      claimName: vega-node-pv-claim
  restartPolicy: Never
  initContainers:
  - name: init-vega-node
    image: data-hub/vega-node
    imagePullPolicy: Never
    command: ["/bin/bash", "-c", "id && ls -al /home/ian && ls -al /mnt/vega-data && cp -r /home/ian/. /mnt/vega-data/"]
    volumeMounts:
    - name: vega-node-pv-storage
      mountPath: /mnt/vega-data
  containers:
  - name: vega-node
    image: data-hub/vega-node
    imagePullPolicy: Never
    resources:
      limits:
        cpu: 700m
      requests:
        cpu: 700m
    volumeMounts:
      - mountPath: /home/ian
        name: vega-node-pv-storage
    securityContext:
      runAsUser: 1000
    command: [ "/bin/bash" ]
    args: [ "-c", 'id && pwd && ls -al . && ls -al .. && sed -i ''/Broker\.Socket/,+7{/Broker\.Socket/,+6{b};s/.*/    Address = ''"\"$BROKER_SERVICE_SERVICE_HOST\""''/}'' .config/vega/node/config.toml; /bin/vega start' ]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vega-node-pv-volume
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: ""
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/vega-node-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vega-node-pv-claim
spec:
  storageClassName: ""
  volumeName: vega-node-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # selector:
  #   matchLabels:
  #     name: vega-node-pv-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: broker-service
  name: broker-service
spec:
  ports:
    - port: 3005
      targetPort: 3005
  selector:
    app: broker-go-pod
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: broker-pod
#   labels:
#     app: broker-pod
# spec:
#   restartPolicy: Never
#   containers:
#   - name: broker
#     image: data-hub/broker
#     imagePullPolicy: Never
#     resources:
#       limits:
#         cpu: 1000m
#       requests:
#         cpu: 1000m
#     env:
#     - name: KAFKA_BROKERS
#       value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
---
apiVersion: v1
kind: Pod
metadata:
  name: broker-go-pod
  labels:
    app: broker-go-pod
spec:
  restartPolicy: Never
  containers:
  - name: broker-go
    image: data-hub/broker-go
    imagePullPolicy: Never
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    env:
    - name: KAFKA_BROKERS
      value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
---
apiVersion: v1
kind: Pod
metadata:
  name: market-data-pod
  labels:
    app: market-data-pod
spec:
  restartPolicy: Never
  containers:
  - name: market-data
    image: data-hub/market-data
    imagePullPolicy: Never
    env:
    - name: KAFKA_BROKERS
      value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
    - name: TIMESCALEDB_HOST
      value: timescaledb-service
    - name: TIMESCALEDB_PORT
      value: "5432"
---
apiVersion: v1
kind: Pod
metadata:
  name: orders-pod
  labels:
    app: orders-pod
spec:
  restartPolicy: Never
  containers:
  - name: orders
    image: data-hub/orders
    imagePullPolicy: Never
    resources:
      limits:
        cpu: 400m
      requests:
        cpu: 400m
    env:
    - name: KAFKA_BROKERS
      value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
    - name: TIMESCALEDB_HOST
      value: timescaledb-service
    - name: TIMESCALEDB_PORT
      value: "5432"
---
apiVersion: v1
kind: Pod
metadata:
  name: deposits-withdrawals-pod
  labels:
    app: deposits-withdrawals-pod
spec:
  restartPolicy: Never
  containers:
  - name: deposits-withdrawals
    image: data-hub/deposits-withdrawals
    imagePullPolicy: Never
    env:
    - name: KAFKA_BROKERS
      value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
    - name: TIMESCALEDB_HOST
      value: timescaledb-service
    - name: TIMESCALEDB_PORT
      value: "5432"
---
apiVersion: v1
kind: Pod
metadata:
  name: markets-pod
  labels:
    app: markets-pod
spec:
  restartPolicy: Never
  containers:
  - name: markets
    image: data-hub/markets
    imagePullPolicy: Never
    env:
    - name: KAFKA_BROKERS
      value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
    - name: TIMESCALEDB_HOST
      value: timescaledb-service
    - name: TIMESCALEDB_PORT
      value: "5432"
---
apiVersion: v1
kind: Pod
metadata:
  name: assets-pod
  labels:
    app: assets-pod
spec:
  restartPolicy: Never
  containers:
  - name: assets
    image: data-hub/assets
    imagePullPolicy: Never
    env:
    - name: KAFKA_BROKERS
      value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
    - name: TIMESCALEDB_HOST
      value: timescaledb-service
    - name: TIMESCALEDB_PORT
      value: "5432"
---
apiVersion: v1
kind: Pod
metadata:
  name: accounts-pod
  labels:
    app: accounts-pod
spec:
  restartPolicy: Never
  containers:
  - name: accounts
    image: data-hub/accounts
    imagePullPolicy: Never
    env:
    - name: KAFKA_BROKERS
      value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
    - name: TIMESCALEDB_HOST
      value: timescaledb-service
    - name: TIMESCALEDB_PORT
      value: "5432"
---
apiVersion: v1
kind: Pod
metadata:
  name: transfers-pod
  labels:
    app: transfers-pod
spec:
  restartPolicy: Never
  containers:
  - name: transfers
    image: data-hub/transfers
    imagePullPolicy: Never
    env:
    - name: KAFKA_BROKERS
      value: "$(KAFKA_SERVICE_SERVICE_HOST):9092"
    - name: TIMESCALEDB_HOST
      value: timescaledb-service
    - name: TIMESCALEDB_PORT
      value: "5432"
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: data-access
# spec:
#   containers:
#   - name: alpine
#     image: alpine:latest
#     command: ['sleep', 'infinity']
#     volumeMounts:
#     - name: vega-node-pv-storage
#       mountPath: /data
#   volumes:
#   - name: vega-node-pv-storage
#     persistentVolumeClaim:
#       claimName: vega-node-pv-claim
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: positions-test
#   name: positions-test
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: positions-test
#   template:
#     metadata:
#       labels:
#         app: positions-test
#     spec:
#       containers:
#       - name: positions
#         image: data-hub:positions
#         imagePullPolicy: Never
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: compute-test
#   name: compute-test
# spec:
#   replicas: 1
#   selector:
#     mathLabels:
#       app: compute-test
#   template:
#     metadata:
#       labels:
#         app: compute-test
#     spec:
#       containers:
#       - name: compute
#         image: data-hub:compute
#         imagePullPolicy: Never
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: zookeeper-service
#   name: zookeeper-service
# spec:
#   type: NodePort
#   ports:
#     - name: zookeeper-port
#       port: 2181
#       nodePort: 30181
#       targetPort: 2181
#   selector:
#     app: zookeeper-test
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: zookeeper-test
#   name: zookeeper-test
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: zookeeper-test
#   template:
#     metadata:
#       labels:
#         app: zookeeper-test
#     spec:
#       containers:
#       - name: zookeeper
#         image: bitnami/zookeeper
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 2181
#         env:
#         - name: ALLOW_ANONYMOUS_LOGIN
#           value: "yes"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: kafka
#   name: kafka-service
# spec:
#   ports:
#     - port: 9092
#       targetPort: 9093
#   selector:
#     app: kafka
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: kafka
#   name: kafka
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: kafka
#   template:
#     metadata:
#       labels:
#         app: kafka
#     spec:
#       containers:
#       - name: kafka
#         image: bitnami/kafka
#         imagePullPolicy: Always 
#         ports:
#         - containerPort: 9092
#         env:
#         - name: KAFKA_CFG_BROKER_ID
#           value: "0"
#         - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
#           value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
#         - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
#           value: CLIENT
#         - name: KAFKA_CFG_LISTENERS
#           value: CLIENT://:9092,EXTERNAL://:9093
#         - name: KAFKA_CFG_ADVERTISED_LISTENERS
#           value: CLIENT://127.0.0.1:9092,EXTERNAL://kafka-service:9092
#         - name: KAFKA_CFG_ZOOKEEPER_CONNECT
#           value: zookeeper-service:2181
#         - name: KAFKA_CFG_AUTO_CREATE_TOPICS
#           value: 'true'
#         - name: ALLOW_PLAINTEXT_LISTENER
#           value: 'yes'
#         - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#           value: "1"