# Manifest file for defining the timescale Deployment and Service in Kubernetes
apiVersion: v1
kind: Service
metadata:
  labels:
    app: timescaledb-service
  name: timescaledb-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: timescaledb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: timescaledb
  name: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - name: timescaledb
        image: timescale/timescaledb
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: ilovetimescaledb